version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  springboot-app:
    image: devraman/student-mgmt:latest
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/students
    depends_on:
      - mongodb

  frontend:
    image: devraman/student-mgmt-frontend:v1
    ports:
      - "3000:3000"
    depends_on:
      - springboot-app
