apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-react-app
  labels:
    app: student-react-app
  namespace: student-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-react-app
  template:
    metadata:
      labels:
        app: student-react-app
    spec:
      containers:
        - name: student-react-app
          image: devraman/student-mgmt-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: student-react-app
  namespace: student-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: student-react-app
