apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: student-namespace
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongodb