apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-springboot-app
  labels:
    app: student-springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-springboot-app
  template:
    metadata:
      labels:
        app: student-springboot-app
    spec:
      containers:
        - name: student-springboot-app
          image: devraman/student-mgmt:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/students
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: student-springboot-app
